class_name Balance
extends RefCounted
## Central balance config (Phase 3, content/balance/). Two halves:
##  1. ENTRIES - per-hero tuning multipliers (designers edit these .tres,
##     never code). Applied once at spawn by HeroFactory; server-side.
##  2. BANDS - per-role DPS/HP sanity bands enforced by the headless
##     balance test (tests/test_roster.tscn generates the table from this
##     config, per the roadmap "balance table generated by test").
##
## Baseline pass: every multiplier is 1.0 (kit values are the first
## balance sheet). Tighten bands and nudge entries as identity settles.

const ENTRIES: Array = [
	preload("res://content/balance/entries/kestrel.tres"),
	preload("res://content/balance/entries/blitz.tres"),
	preload("res://content/balance/entries/bastion.tres"),
	preload("res://content/balance/entries/mira.tres"),
	preload("res://content/balance/entries/patch.tres"),
	preload("res://content/balance/entries/nimbus.tres"),
]

## Role bands (loose now, tightened as the six identities settle).
## dps = 2 s-window harness DPS vs a standard dummy; hp = kit max_hp.
const BANDS: Dictionary = {
	"ASSAULT":    {"min_dps": 45.0, "max_dps": 135.0, "min_hp": 90.0},
	"TANK":       {"min_dps": 8.0, "max_dps": 30.0, "min_hp": 180.0},
	"SUPPORT":    {"min_dps": 30.0, "max_dps": 90.0, "min_hp": 90.0},
	"CONTROLLER": {"min_dps": 35.0, "max_dps": 75.0, "min_hp": 80.0},
}

static func entry_for(hero_id: String) -> BalanceEntry:
	for e in ENTRIES:
		var entry: BalanceEntry = e
		if entry.hero_id == hero_id:
			return entry
	return null

static func entry_count() -> int:
	return ENTRIES.size()

## Apply a hero's balance entry to a freshly built hero (server-side).
## No-op when the entry is missing (e.g. test dummies without a kit).
static func apply_to(h: Hero, hd: HeroData) -> void:
	if h == null or hd == null:
		return
	var e := entry_for(hd.id)
	if e == null:
		return
	h.max_hp = int(float(hd.max_hp) * e.hp_mult)
	h.base_speed = hd.base_speed * e.speed_mult
	if h.weapon != null:
		h.weapon.damage *= e.damage_mult
		h.weapon.fire_rate *= e.fire_rate_mult
	if h.ability != null:
		h.ability.ult_charge_mult = e.ult_charge_mult
